### ISSUE TITLE
Search strategy

### ISSUE THREAD

**Issue by Michahel** [savanto/AnDICT-Android#3]
There is a need to choose a desired strategy. For example, I personally prefer the word strategy. In the settings there are only two strategies: All matches, First match. Why can not the SHOW STRATEGIES command be used for this list?

**Comment by savanto** [comment]
The "Search strategy" in the app was incorrectly named by me. It is actually the "Database to search". I've renamed this in [v1.2.0](https://github.com/savanto/AnDICT-Android/releases/tag/v1.2.0).

The app currently only implements the [`DEFINE` command](https://tools.ietf.org/html/rfc2229#section-3.2) which only accepts the `database` to search, or `*` for "all matches", or `!` for "first match". It was my intention to eventually populate the list in the preferences with the output of the [`SHOW DATABASES` command](https://tools.ietf.org/html/rfc2229#section-3.5.1).

The search strategies available from [`SHOW STRATEGIES`](https://tools.ietf.org/html/rfc2229#section-3.5.2) are only useful with the [`MATCH` command](https://tools.ietf.org/html/rfc2229#section-3.3) which I have not implemented.

I don't think that `MATCH` is very useful, since it only returns the databases that may have the word in question, rather than the definitions themselves. However, if you would show me an example of how you would use `MATCH` with an appropriate search strategy, I would consider implementing it.

**Comment by Michahel** [comment]
Hi Savanto,

I just got around to looking at it. I was very busy at the moment.

>I don't think that MATCH is very useful, since it only returns the databases that may have the word in >question, rather than the definitions themselves. However, if you would show me an example of how >you would use MATCH with an appropriate search strategy, I would consider implementing it.

Most often I use strategy word. The request "MATCH database strategy word" when strategy=word allows to find such definitions when the required word is part of a phrase. The user thus receives fuller information stored in dictionary bases.
An example would be for using console dict client which is part of the debian.
The request dict dict://localhost/m:"SearchWord":*:word uses strategy 'word'. 

Try running the test.
Do a search on the word "дерево" in Dict:
dict -h dict.bible.ru -s word дерево
Do a search on the word "дерево" in AnDICT.
Compare these two search results.

I understand, that Dict uses about such algorithm of work. 

1. Sends a request in the form: 
dict dict://dict.bible.ru/m:"дерево" 

2. If no matches found for "дерево" the message is displayed: 'No definitions were found for "дерево".' If matches are found, the list is made: 
databasename1 match1, match2..., matchM 
databasename2 match1, match2..., matchM 
...
databasenameN match1, match2..., matchM 

Also item 3 is carried out: 

3. For each element from the list: 
dict dict://dict.bible.ru/d:"match1":databasename1 
... 
dict dict://dict.bible.ru/d:"matchM":databasenameN

**Comment by Michahel** [comment]
Here is the latest source of the Dict: https://github.com/cheusov/dictd/blob/master/dict.c

**Comment by savanto** [comment]
This has been implemented in #9, and released in [v1.3.0](https://github.com/savanto/AnDICT-Android/releases/tag/v1.3.0). Let me know if you have any issues with it!
